
language: node_js
node_js: stable

branches:
  only:
    - hexo
# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo generate

after_script:
  - git config --global user.name "ncc0706"
  - git config --global user.email "ncc0706@gmail.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - cat ./_config.yml
  - hexo deploy
  - ls
# E: Build LifeCycle
env:
 global:
   - GH_REF: github.com/4520/blog.git




